### ISSUE TITLE
Dataset placement and adjustment

### ISSUE THREAD

**Issue by HIN0209** [JunaidMuthukadan/Music-source-seperation-using-recurrent-VAE#1]
@JunaidMuthukadan,

Looks like a very interesting project. While I jumped onto this immediately, I am puzzled how and where I should place the DSD dataset and modify the code accordingly. Please instruct.
Thank you!

**Comment by JunaidMuthukadan** [comment]
Please provide your details and for what purpose you are taking this code
it's still in development phase.
I have to add licence and everything in to it.

Thank yiu

**Comment by JunaidMuthukadan** [comment]
you can place in the root with folder name "dataset/DSD100"

**Comment by HIN0209** [comment]
@JunaidMuthukadan 
Thank you for the commitment to show the location. I also guessed that the folderpath of DSD.xml to be changed. 
I will try how it works!!
